### ISSUE TITLE
Why should NOASSERTION be the curated license description merely because there is no SPDX identifier?

### ISSUE THREAD

**Issue by richardfontana** [clearlydefined/clearlydefined#99]
According to the [Curation Guidelines](https://github.com/clearlydefined/clearlydefined/blob/master/docs/curation-guidelines.md) : 

> Use the license resulting from analyzing the content of the file. If the result cannot be interpreted as an SPDX-listed license identifier, treat it as NOASSERTION.
 
and 

> Canonicalize the identifier with an SPDX-listed license identifier and use. If the value cannot be canonicalized, treat as NOASSERTION.

I don't understand the rationale for this, in cases where it is possible to provide some meaningful, if perhaps ad hoc or nonstandard, description for a license. An example is given in https://github.com/clearlydefined/curated-data/pull/1107

Code that is under the Facebook React-style license scheme, which is pretty well known, will be treated as "NOASSERTION" even though there is a well understood assertion (i.e., BSD-2-Clause [which itself is an SPDX identifier] plus a nonstandard separate file with a patent license grant.

The reason this is relevant: the universe of adopted SPDX identifiers is so much smaller than the universe of identifiable licenses encountered in FOSS code. That may be less true of the kinds of software that has up to now been the focus of ClearlyDefined definitions, but for example if you start to expand coverage to the package ecosystems seen in server/desktop Linux distributions you quickly see the (current) inadequacy of SPDX as an accurate license description system.

**Comment by fossygirl** [comment]
@jeffmcaffer Thoughts here?

**Comment by jeffmcaffer** [comment]
@richardfontana absolutely. The challenge is more pedestrian than philosophical. We formulate license expressions and do license algebra across different tool output as well as across files. As such, we need a canonical way to talk about license A vs license B. Not so much the semantics of the license (we don't do interpretation or compatibility anyway) but rather just the simple identity. SPDX has the ability to capture non-listed licenses using `LicenseRef-XXX` syntax. To cover the licenses you mention, we need the XXX part corresponding to each license.

Ideally these extended license identifiers would be normalized and deduplicated so that multiple tools discovering the same license would render the same identifiers. Given that, ClearlyDefined is quite agnostic to the actual labels used for any given license.

Interestingly there are at least three different discussions I've seen on how to handle this in SPDX (there is a current thread on the SPDX-tech list. see https://lists.spdx.org/g/Spdx-tech/message/3662. I have replied there but some reason it is not showing up) . 

While I have my personal instincts, as long as the approach is workable, I'm fine. For our part, ClearlyDefined would be more than happy to support a registry of more dynamic SPDX identifiers and provide that as a service.

**Comment by nickvidal** [comment]
Given recent work on LicenseRef and upgrade to the latest Scancode, we might want to revisit the Curation guidelines. Closing this issue for now.
